### ISSUE TITLE
[feature request] contribution guide

### ISSUE THREAD

**Issue by SKalt** [mohd-akram/languages#11]
Adding a guide on how to contribute missing nodes or edges would be helpful.  Is the correct procedure adding the new compilers to https://github.com/mohd-akram/compilers and re-generating ./js/compilers.js?

**Comment by waldyrious** [comment]
@SKalt please review #14, whose aims include addressing this need. I am also curious about the "re-generating ./js/compilers.js" step, though -- hopefully @mohd-akram can clarify that point.

**Comment by mohd-akram** [comment]
Well, right now it's treated like the other libraries in the repo (eg. cytoscape), updated every now and then. I had removed the generated JS file in the compilers repo to make PRs easier there, otherwise I'd link to it in the script tag.

**Comment by SKalt** [comment]
@waldyrious, #14 does close this.  How to manage The periodic updates remains unclear, but now falls under dependency management. I'd recommend  adopting either `npm` or `yarn` so you can `npm install --save https://github.com/mohd-akram/compilers`.  That would require adopting a bundler, which I could help with.

**Comment by waldyrious** [comment]
For what it's worth, at [tldr-pages](https://github.com/tldr-pages/tldr) we use Travis to [automatically make commits](https://github.com/tldr-pages/tldr-pages.github.io/commits/master) to another repo that keeps an archive of all the commands in the original repo, as soon as any commits is merged in. To see how we set it up, check [the travis.yml file](https://github.com/tldr-pages/tldr/blob/master/.travis.yml) and [the build.sh script](https://github.com/tldr-pages/tldr/blob/master/scripts/build.sh) it calls to do that.

Something like that could certainly be adapted to work here, so that no manual work (by contributors and maintainers alike) would be necessary :) what do you guys think?

**Comment by SKalt** [comment]
I like the "no work required" part.  If you want to set it up, you've got
my support.  Any thoughts on `git subtree` and `git submodule` to manage
the other repo as a dependency?

**Comment by waldyrious** [comment]
> Any thoughts on `git subtree` and `git submodule` to manage the other repo as a dependency?

They certainly would work, as would build tools like those you mentioned; but neither would be automatic, "no work required", which for the purposes of this demo I think would be preferable.

**Comment by SKalt** [comment]
I agree they'd be more work, at least for now.  I'm still wrestling with automating `git sub(tree|module)`  to coordinate two apps and a library for work.  Hopefully I'll get that done and be able to disagree in the future :)
